---
title: "plinkQC"
author: "Crystal Shan"
date: "2025-07-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(plinkQC)
indir="/Users/crystal/Downloads/nl/human/skin/eQTLs/donor_genotyping/hg38/plinkQC/genodata"
qcdir="/Users/crystal/Downloads/nl/human/skin/eQTLs/donor_genotyping/hg38/plinkQC/genodata"
name <- "data" # # Because your files are test.bed, test.bim, test.fam
path2plink <- "/Users/crystal/Downloads/plink_mac_20250615/plink"

fail_individuals <- perIndividualQC(
  indir = indir,
  qcdir = qcdir,
  name = name,
  path2plink = path2plink,
  refSamplesFile = file.path(qcdir, "HapMap_ID2Pop.txt"),
  refColorsFile = file.path(qcdir, "HapMap_PopColors.txt"),
  prefixMergedDataset = file.path(qcdir, "data.HapMapIII"),  # only if you downloaded this .bed/.bim/.fam set (not just eigenvec)
  do.run_check_ancestry = FALSE,
  interactive = TRUE,
  verbose = TRUE,
  showPlinkOutput=TRUE
)


```
# per marker quality control
```{r markerQC}
fail_markers <- perMarkerQC(indir=indir, qcdir=qcdir, name=name,
                            path2plink=path2plink,
                            verbose=TRUE, interactive=TRUE,
                            showPlinkOutput=TRUE)

```
# check ancestry
```{r ancestry}
library(plinkQC)
indir="/Users/crystal/Downloads/nl/human/skin/eQTLs/donor_genotyping/hg38/plinkQC/genodata"
name <- "data" # # Because your files are test.bed, test.bim, test.fam
path2plink <- "/Users/crystal/Downloads/plink_mac_20250615/plink"
refname <- 'HapMapIII_CGRCh38'
prefixMergedDataset <- paste(name, ".", refname, sep="")

exclude_ancestry <-
    evaluate_check_ancestry(indir=indir, name=name,
                            prefixMergedDataset=prefixMergedDataset,
                            refSamplesFile=paste(indir, "/HapMap_ID2Pop.txt",
                                                 sep=""), 
                            refColorsFile=paste(indir, "/HapMap_PopColors.txt",
                                                sep=""),
                            verbose=TRUE,
                            interactive=TRUE)
```