---
title: "commonly-induced-vs-cellTypeSpecicallyInduced-promoters"
author: "Crystal Shan"
date: "2024-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages  
```{r package, warning=FALSE, include=FALSE}
library(dplyr)
library(magrittr)
library(tidyverse)
library(gplots)
library(ggfortify)
library(gridExtra)
library(grid)
library(cowplot)
library(ggpubr)
library(DESeq2)
library(ComplexHeatmap)

Dir="~/Downloads/nl/human/skin/eQTLs/integrative_analysis"
setwd(Dir)

outDir="~/Downloads/nl/human/skin/eQTLs/integrative_analysis/gene_cluster_overlapping_TFpeak"

load(paste0(Dir,"/heatmap_RNA_round2/myEnvironment_heatmap_RNAseq_DEgenes_14kmm-hc_04182023_padj0.05_log2FC1.5_avgCPM10.RData"))
res.atac.dds.frb = readRDS("~/Downloads/nl/human/skin/eQTLs/ATACseq_DolphinNext/DESeq2/DESeq2_results_ATACseq_peaks_1kb_FRB.Rdata")
res.atac.dds.krt = readRDS("~/Downloads/nl/human/skin/eQTLs/ATACseq_DolphinNext/DESeq2/DESeq2_results_ATACseq_peaks_1kb_KRT.Rdata")
res.atac.dds.mel = readRDS("~/Downloads/nl/human/skin/eQTLs/ATACseq_DolphinNext/DESeq2/DESeq2_results_ATACseq_peaks_1kb_MEL.Rdata")
res.chip.dds.frb = readRDS("~/Downloads/nl/human/skin/eQTLs/ChIP-seq/DESeq2/DESeq2_results_H3K27acChIPseq_peaks_1kb_FRB.Rdata")
res.chip.dds.krt = readRDS("~/Downloads/nl/human/skin/eQTLs/ChIP-seq/DESeq2/DESeq2_results_H3K27acChIPseq_peaks_1kb_KRT.Rdata")
res.chip.dds.mel = readRDS("~/Downloads/nl/human/skin/eQTLs/ChIP-seq/DESeq2/DESeq2_results_H3K27acChIPseq_peaks_1kb_MEL.Rdata")
link_gene_promoter = readRDS(paste0(Dir,"/heatmap_RNA_round2/link_gene_promoter_within_300kbp_of_TSS_allcts.Rdata"))
link_gene_enhancer = readRDS(paste0(Dir,"/heatmap_RNA_round2/link_gene_enhancer_within_300kbp_of_TSS_allcts.Rdata"))
FRB_cRE_dynamics = readRDS(paste0(Dir,"/heatmap_RNA_round2/FRB_gene_and_cRE_RNA_ATAC_and_H3K27ac_dynamics.Rdata"))
MEL_cRE_dynamics = readRDS(paste0(Dir,"/heatmap_RNA_round2/MEL_gene_and_cRE_RNA_ATAC_and_H3K27ac_dynamics.Rdata"))
KRT_cRE_dynamics = readRDS(paste0(Dir,"/heatmap_RNA_round2/KRT_gene_and_cRE_RNA_ATAC_and_H3K27ac_dynamics.Rdata"))
FRB_cRE_dynamics = readRDS(paste0(Dir,"/heatmap_RNA_round2/FRB_gene_and_cRE_RNA_ATAC_and_H3K27ac_dynamics.Rdata"))
bed <- data.table::fread("~/Downloads/nl/human/skin/eQTLs/chromatin/RegulatoryElements/method3/regulatory_regions.bed")
colnames(bed) <- c("chr","start","end","region")
df3 = readRDS(paste0(Dir,"/heatmap_RNA_round2/enhancer_count_by_gene.rds"))
CPM.pbs <- CPM_rna %>% dplyr::select(contains("_PBS_")) %>% set_colnames(gsub("_PBS","",colnames(.)))
CPM.ifn <- CPM_rna %>% dplyr::select(contains("_IFN_")) %>% set_colnames(gsub("_IFN","",colnames(.)))
log2FC_rna=log2((CPM.ifn+10)/(CPM.pbs+10))
```
## functions for plotting
```{r paired_plot_function, eval=FALSE, echo=FALSE, include=FALSE}
make_paired_plot <- function(this.title,this.df) {
  df = data.frame(CPM=as.numeric(this.df[1,]), sample=colnames(this.df)) %>%
    separate( . , col=sample, into=c("donor","treatment","celltype")) 
  df$treatment <- factor(df$treatment, levels = c("PBS","IFN"))
  
  position <- "identity"; width = 0.5; point.size = 2; line.size = 0.5
  line.color = "grey"; linetype = "solid"; palette="bright"
  
  highlightdata1 <- df %>% filter(donor=="F25")
  highlightdata2 <- df %>% filter(donor=="F49")
  highlightdata3 <- df %>% filter(donor=="F55")
  
  p <- ggplot(df, create_aes(list(x = "treatment", y = "CPM"))) +
    geom_exec(geom_line, data = df, group = "donor",
              color = line.color, size = line.size, linetype = linetype,
              position = position) +
    geom_exec(geom_point, data = df, color = "treatment", size = point.size,
              position = position) +
    scale_color_manual(values=c("#999999", "#E69F00")) +
    geom_exec(geom_line, data = highlightdata1, group = "donor",
              color = "blue", size = 0.7, linetype = linetype,
              position = position) +
    geom_exec(geom_line, data = highlightdata2, group = "donor",
              color = "brown", size = 0.7, linetype = linetype,
              position = position) +
    geom_exec(geom_line, data = highlightdata3, group = "donor",
              color = "black", size = 0.7, linetype = linetype,
              position = position) +
    ggtitle(this.title) +
    theme(legend.position="none") +
    theme(plot.title = element_text(size = 10, face = "bold")) +
    facet_wrap(~ celltype)
  p
  return(p)
}
```
```{r paired_plot_makePDF}
gene_lst = neg_control_list
gene_lst_name="neg_control_list"

plot_list <- c()
for (i in 1:length(gene_lst)) {
  g <- gene_lst[i]
  p <- make_paired_plot(g,CPM_rna[g,])
  plot_list[[i]] <- p
}

pdf(paste0(outDir,"/paired_plots_",gene_lst_name,".pdf"),width=15,height=8)
for (i in 1:length(plot_list)) {
  print(plot_list[[i]])
}
dev.off()
```
## plot heatmap to check which clusters I should pick
```{r plotheatmap}
# km_res.rna.new variable is loaded in line28 from script heatmap_RNA_round2/3cts_interactive_heatmap_RNAseq_ATACseq_ChIPseq_version2.Rmd
split_instructions.new <- km_res.rna.new$newclass

# 4. load genes of interest
g <- data.table::fread("~/Downloads/nl/human/skin/eQTLs/literature/KEGG/GSEA_hallmark-genes-upregulated-in-response-to-IFNG.txt",header=F)$V1
zlogCPM.heatmap.new <- km_res.rna.new[,1:ncol(CPM_rna_DEG)]
zlogCPM.heatmap_with_gene <- zlogCPM.heatmap.new %>% dplyr::filter(rownames(.) %in% g)
row_anno_index <- which(rownames(zlogCPM.heatmap.new) %in% rownames(zlogCPM.heatmap_with_gene))
row_anno_label <- rownames(zlogCPM.heatmap.new)[row_anno_index]

# 5. plot heatmap
column_ha = HeatmapAnnotation(
  condition = colnames(zlogCPM.heatmap.new) %>% 
    lapply( . , function(x) unlist(strsplit(x , "_", ))[2]) %>% unlist(),
  celltype = colnames(zlogCPM.heatmap.new) %>% 
    lapply( . , function(x) unlist(strsplit(x , "_", ))[3]) %>% unlist(),
  col = list(condition = c("PBS" = "black", "IFN" = "#FA8072"),
             celltype = c("KRT" = "#DAF7A6", "MEL" = "#964B00", "FRB" = "#CCCCFF")),
  show_legend = c(TRUE,TRUE))

row_ha = rowAnnotation(
  foo = anno_mark(at = row_anno_index, 
                  labels = row_anno_label,
                  which="row",
                  labels_gp = gpar(fontsize=10),
                  padding=unit(0.5,"mm")))

pdf(paste0(outDir,"/heatmap_reordered_RNAseq_DEgenes_14kmm-hc_padj0.05_log2FC1.5_avgCPM10.pdf"),width=24,height=30)
heatmap.rna <- draw(Heatmap(zlogCPM.heatmap.new, 
                            name = "z-score log2CPM",
                            top_annotation = column_ha,
                            right_annotation = row_ha,
                            column_title = "DE genes in 3 celltypes, control vs IGNg stimulated, known IFNg inducible genes labeled",
                            cluster_columns = FALSE,
                            cluster_rows = FALSE,
                            column_split = c(rep(1,length(colnames(CPM_rna_DEG)[grepl("PBS_KRT",colnames(CPM_rna_DEG))])), 
                                             rep(2,length(colnames(CPM_rna_DEG)[grepl("PBS_MEL",colnames(CPM_rna_DEG))])), 
                                             rep(3,length(colnames(CPM_rna_DEG)[grepl("PBS_FRB",colnames(CPM_rna_DEG))])), 
                                             rep(4,length(colnames(CPM_rna_DEG)[grepl("IFN_KRT",colnames(CPM_rna_DEG))])), 
                                             rep(5,length(colnames(CPM_rna_DEG)[grepl("IFN_MEL",colnames(CPM_rna_DEG))])),
                                             rep(6,length(colnames(CPM_rna_DEG)[grepl("IFN_FRB",colnames(CPM_rna_DEG))]))),
                            row_split = split_instructions.new, 
                            show_row_names = FALSE,
                            row_title_rot = 0,
                            column_names_rot = 45,
                            row_gap = unit(0, "mm"),
                            border = TRUE,
                            column_names_gp = gpar(fontsize = 10),
                            column_title_gp = gpar(fontsize = 10, fontface = "bold"),
                            row_title_gp = gpar(fontsize = 10, fontface = "bold")))
dev.off()


```
# analysis 1. cluster10
## Cluster 10 is melanocyte-specifically-induced gene cluster. It's the only cluster that has low expression in all celltypes in PBS but specifically induced in one cell type upon IFNg.
```{r analysis1-fetch-cluster10-promoter}
# get gene list, 81 genes
gene_list <- rownames(km_res.rna.new)[which(km_res.rna.new$newclass==10)]

# only keep the 53 genes that are lowly expressed in PBS and induced in IFNg
pruned_gene_list <- c()
for (i in 1:length(gene_list)){
  g = gene_list[i]
  exprs.pbs.krt <- CPM_rna[g,] %>% dplyr::select(ends_with("_PBS_KRT")) %>% as.numeric()
  exprs.pbs.mel <- CPM_rna[g,] %>% dplyr::select(ends_with("_PBS_MEL")) %>% as.numeric()
  exprs.pbs.frb <- CPM_rna[g,] %>% dplyr::select(ends_with("_PBS_FRB")) %>% as.numeric()
  is_lowly_expressed_in_PBS_3cts = (mean(exprs.pbs.krt) <= 10 & mean(exprs.pbs.mel) <= 10 & mean(exprs.pbs.frb) <= 10)
  log2fc.krt <- log2FC_rna[g,] %>% dplyr::select(ends_with("_KRT")) %>% as.numeric()
  log2fc.mel <- log2FC_rna[g,] %>% dplyr::select(ends_with("_MEL")) %>% as.numeric()
  log2fc.frb <- log2FC_rna[g,] %>% dplyr::select(ends_with("_FRB")) %>% as.numeric()
  is_specifically_induced_in_MEL = (mean(log2fc.mel) >= 0.5 & mean(log2fc.krt) < 0.5 & mean(log2fc.frb) < 0.5)
  if (is_lowly_expressed_in_PBS_3cts & is_specifically_induced_in_MEL) {
    pruned_gene_list <- c(pruned_gene_list, g)
  }
}

# get promoter list. 71 unique promoters.
promoter_df <- link_gene_promoter %>% dplyr::filter(gene %in% gene_list)
promoter_bed <- bed %>% dplyr::filter(region %in% promoter_df$promoter)
data.table::fwrite(promoter_bed, file=paste0(outDir,"/MEL_specifically_induced_promoters.bed"),quote=F, sep="\t",col.names=F, row.names=F)






freq_df <- table(promoter_df[,c("region")]) %>% as.data.frame()
table(freq_df$Freq)
# 21 promoters are only in 1 celltype (17 are in MEL), 7 promoters are in 2 celltypes, and 12 promoters are in all celltypes.
View(promoter_df[which(promoter_df$region %in% freq_df[which(freq_df$Freq==1),"region"]),])
View(promoter_df[which(promoter_df$region %in% freq_df[which(freq_df$Freq==2),"region"]),])

# promoters in only melanocytes
temp <- table( promoter_df[,c("region")]) %>% as.data.frame() %>% dplyr::filter(Freq==1) %>% pull(region) %>% as.character()
promoter_list <- promoter_df %>% dplyr::filter(region %in% temp & celltype=="MEL") %>% pull(region) %>% unique()
promoter_bed <- bed %>% dplyr::filter(region %in% promoter_list)
data.table::fwrite(promoter_bed, file=paste0(outDir,"/MEL_specifically_induced_promoters.bed"),quote=F, sep="\t",col.names=F, row.names=F)

```

```{r compile-table}
#### load TF ChIPseq overlap result
TF_overlap <- data.table::fread(paste0(outDir,"/MEL_specifically_induced_genes_promoter_overlapping_TF_peaks.bed"))
colnames(TF_overlap) <- c("chr","start","end","promoter","TF","entry")
tab <- left_join(promoter_df, TF_overlap, by="promoter") %>% na.omit()

#### check which TF are linked to which gene
gene_TF <- tab %>% dplyr::select(c(gene,TF)) %>% distinct()
gene_TF_n <- gene_TF %>% group_by(TF) %>% mutate(count = n()) %>% dplyr::select(c(TF,count)) %>% distinct()
gene_TF_summary <- gene_TF %>% group_by(TF) %>% summarize(gene=paste(gene,collapse=",")) %>%
  left_join(gene_TF_n, . , by="TF")

data.table::fwrite(gene_TF_summary, file=paste0(outDir,"/ENCODE_TF_peak_intersecting_promoters_of_MEL_specifically_induced_genes_summary.txt"),
                   quote=F, sep="\t", row.names=F, col.names=T)

```
